### ISSUE TITLE
Construir protótipo

### ISSUE THREAD

**Issue by alessandrojsouza** [lades-cnat/lades#6]
Construir o protótipo de alta fidelidade do projeto usando FIGMA.

**Comment by alessandrojsouza** [comment]
Refinar (CSS) com a professora Danielle ou Silvia.

**Comment by JoseJefferson304** [comment]
https://www.figma.com/file/UNNPvBGPlHyFq0aY00qfZD/Untitled?type=design&node-id=0-1&mode=design&t=zjKKUPAbkvrONVy1-0
